//! Automatic per-turn recaps.
//!
//! Recaps are generated on the desktop from local assistant transcripts after
//! each completed turn. The cloud/dashboard only receives the finished recap,
//! not the raw transcript used to produce it.

use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use regex::Regex;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::cli::RecapCommand;
use crate::config::Config;
use crate::git::GitState;
use crate::platforms::{PlatformKind, PlatformStats, SessionState};
use crate::slack::{extract_threads, SlackThread};
use crate::title::clean_generated_title;

pub const DEFAULT_RECAP_MODEL: &str = "claude-haiku-4-5";
const ANTHROPIC_MESSAGES_URL: &str = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_VERSION: &str = "2023-06-01";
const MAX_TRANSCRIPT_CHARS: usize = 28_000;
const MAX_TOOL_RESULT_CHARS: usize = 1_200;
/// How long the "Recaps enabled" startup toast remains visible.
pub const ENABLED_TOAST_DURATION: Duration = Duration::from_secs(10);

/// Current recap status shown in the terminal handoff strip.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecapStatus {
    Disabled,
    MissingKey,
    Waiting,
    Updating,
    Ready,
    Failed(String),
}

/// Turn-scoped line delta shown on the right side of the recap strip.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub struct TurnLineDelta {
    pub additions: i64,
    pub deletions: i64,
}

impl TurnLineDelta {
    fn between(before: &GitLineSnapshot, after: &GitLineSnapshot) -> Self {
        Self {
            additions: after.additions as i64 - before.additions as i64,
            deletions: after.deletions as i64 - before.deletions as i64,
        }
    }
}

/// Display-ready generated recap.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub struct TurnRecap {
    pub prompt_count: u32,
    pub generated_at: u64,
    /// Codex-only session title generated by this recap pass.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub variant: RecapVariant,
    pub headline: String,
    pub bullets: Vec<String>,
    pub next_prompt_notes: Vec<String>,
    pub artifacts: Vec<String>,
    pub line_delta: TurnLineDelta,
    /// Per-PR progress judgments from the same generation pass.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pr_notes: Vec<PrRecapNote>,
    /// Slack message links pasted in the prompt for this turn.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub slack_threads: Vec<SlackThread>,
}

/// The model's read on one tracked PR: a short progress note and how
/// confident it is that the PR is finished.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub struct PrRecapNote {
    pub url: String,
    pub note: String,
    /// high / medium / low — confidence that the PR is done.
    pub confidence: String,
}

/// Snapshot of one tracked PR handed to the recap prompt.
#[derive(Clone, Debug)]
pub struct PrBrief {
    pub url: String,
    /// `repo #123 — title`.
    pub label: String,
    /// OPEN / DRAFT / MERGED / CLOSED plus a compact CI summary.
    pub status: String,
    pub primary: bool,
}

/// Compact or bullet recap rendering mode.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[serde(rename_all = "lowercase")]
pub enum RecapVariant {
    Brief,
    Bullets,
}

/// State consumed by the terminal renderer.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecapState {
    pub enabled: bool,
    pub status: RecapStatus,
    pub latest: Option<TurnRecap>,
    pub line_delta: Option<TurnLineDelta>,
    pub model: String,
}

impl RecapState {
    /// Whether the handoff strip is hosting a real recap (rather than the
    /// toast or hint paths). Kept as a small helper for tests and future
    /// callers that want to distinguish "actual recap content" from the
    /// transient enable/disable messaging.
    #[allow(dead_code)]
    pub fn prefers_handoff(&self) -> bool {
        self.latest.is_some() || matches!(self.status, RecapStatus::Failed(_))
    }
}

impl Default for RecapState {
    fn default() -> Self {
        Self {
            enabled: false,
            status: RecapStatus::Disabled,
            latest: None,
            line_delta: None,
            model: DEFAULT_RECAP_MODEL.to_string(),
        }
    }
}

#[derive(Clone, Copy, Debug, Default)]
struct GitLineSnapshot {
    additions: usize,
    deletions: usize,
}

impl GitLineSnapshot {
    fn from_git_state(git: &GitState) -> Self {
        Self {
            additions: git.files.iter().map(|f| f.additions).sum(),
            deletions: git.files.iter().map(|f| f.deletions).sum(),
        }
    }
}

#[derive(Clone, Debug)]
struct TurnBaseline {
    prompt_count: u32,
    git_lines: GitLineSnapshot,
}

#[derive(Clone)]
struct RecapJob {
    platform: PlatformKind,
    transcript_path: Option<PathBuf>,
    prompt_count: u32,
    model: String,
    api_key: String,
    line_delta: TurnLineDelta,
    /// Tracked PRs at generation time, for per-PR progress notes.
    prs: Vec<PrBrief>,
}

/// Owns turn detection, background recap generation, and the display cache.
pub struct RecapManager {
    state: RecapState,
    api_key: Option<String>,
    last_prompt_count: u32,
    last_completion_count: u32,
    initialized: bool,
    active_turn: Option<TurnBaseline>,
    pending: Option<mpsc::Receiver<std::result::Result<TurnRecap, String>>>,
    /// Wall-clock anchor used to fade the startup confirmation toast.
    started_at: Instant,
    /// All successful recaps generated in this session, oldest first. Mirrors
    /// the title_history pattern so the dashboard can replay the full timeline.
    history: Vec<TurnRecap>,
    /// Tracked PRs to judge in the next generation, set fresh each tick.
    pr_context: Vec<PrBrief>,
}

impl RecapManager {
    pub fn load() -> Self {
        let config = Config::load().unwrap_or_default();
        let api_key = Config::read_recap_api_key()
            .ok()
            .flatten()
            .or_else(read_anthropic_api_key_env);
        let model = config
            .recap_model
            .unwrap_or_else(|| DEFAULT_RECAP_MODEL.to_string());
        let status = if config.recap_enabled {
            if api_key.is_some() {
                RecapStatus::Waiting
            } else {
                RecapStatus::MissingKey
            }
        } else {
            RecapStatus::Disabled
        };

        Self {
            state: RecapState {
                enabled: config.recap_enabled,
                status,
                latest: None,
                line_delta: None,
                model,
            },
            api_key,
            last_prompt_count: 0,
            last_completion_count: 0,
            initialized: false,
            active_turn: None,
            pending: None,
            started_at: Instant::now(),
            history: Vec::new(),
            pr_context: Vec::new(),
        }
    }

    /// Hand the recap generator the session's tracked PRs so each turn's
    /// recap can judge their progress alongside the summary.
    pub fn set_pr_context(&mut self, prs: &[crate::pr::SessionPr]) {
        self.pr_context = prs
            .iter()
            .filter(|pr| !pr.dismissed)
            .map(|pr| {
                let title = if pr.title.is_empty() {
                    String::new()
                } else {
                    format!(" — {}", pr.title)
                };
                let state = if pr.is_draft && pr.state == "OPEN" {
                    "DRAFT"
                } else {
                    pr.state.as_str()
                };
                let checks = if pr.checks_total > 0 {
                    format!(
                        ", CI {}✓ {}✗ {}●",
                        pr.checks_passed, pr.checks_failed, pr.checks_pending
                    )
                } else {
                    String::new()
                };
                PrBrief {
                    url: pr.url.clone(),
                    label: format!("{} #{}{}", pr.repo, pr.number, title),
                    status: format!("{state}{checks}"),
                    primary: pr.primary,
                }
            })
            .collect();
    }

    pub fn state(&self) -> &RecapState {
        &self.state
    }

    /// All successful recaps generated this session, oldest first.
    pub fn history(&self) -> &[TurnRecap] {
        &self.history
    }

    /// Whether the transient "Recaps enabled" toast should be shown.
    ///
    /// True only while recaps are armed with a usable key (Waiting / Updating /
    /// Ready) and within the first `ENABLED_TOAST_DURATION` of the session.
    pub fn enabled_toast_visible(&self) -> bool {
        if self.started_at.elapsed() >= ENABLED_TOAST_DURATION {
            return false;
        }
        matches!(
            self.state.status,
            RecapStatus::Waiting | RecapStatus::Updating | RecapStatus::Ready
        )
    }

    pub fn state_hash(&self) -> u64 {
        use std::hash::{Hash, Hasher};

        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        self.state.enabled.hash(&mut hasher);
        format!("{:?}", self.state.status).hash(&mut hasher);
        self.state.model.hash(&mut hasher);
        self.state.line_delta.hash(&mut hasher);
        self.state.latest.hash(&mut hasher);
        if let Some(latest) = &self.state.latest {
            recap_age_bucket(latest.generated_at).hash(&mut hasher);
        }
        // Time-sensitive: included so the redraw tick clears the toast at
        // the 10-second mark even when no other state has changed.
        self.enabled_toast_visible().hash(&mut hasher);
        hasher.finish()
    }

    /// Optimistically clear the recap card when we know a new prompt was just
    /// submitted, without waiting for the platform's prompts counter to tick.
    ///
    /// Called from the keyboard input path when Enter fires in Ready/Complete
    /// state, before Codex/Claude has flushed its log line. Mirrors the
    /// `stats.prompts > last_prompt_count` branch in `handle_platform_update`,
    /// so when the real platform update lands it's a no-op.
    ///
    /// Returns true if the visible recap state changed.
    pub fn note_user_submitted_prompt(&mut self) -> bool {
        // Nothing to clear if the card was already empty or in an updating /
        // disabled state.
        if self.state.latest.is_none() && !matches!(self.state.status, RecapStatus::Ready) {
            return false;
        }
        self.state.latest = None;
        self.state.line_delta = Some(TurnLineDelta::default());
        self.pending = None;
        self.active_turn = None;
        self.state.status = if self.state.enabled {
            if self.api_key.is_some() {
                RecapStatus::Waiting
            } else {
                RecapStatus::MissingKey
            }
        } else {
            RecapStatus::Disabled
        };
        true
    }

    /// Update turn tracking from the latest platform stats.
    ///
    /// Returns true when renderable recap state changed.
    pub fn handle_platform_update(
        &mut self,
        platform: PlatformKind,
        stats: &PlatformStats,
        effective_state: SessionState,
        git_state: &GitState,
        cwd: &Path,
    ) -> bool {
        let mut changed = self.poll_pending(cwd);

        if !self.initialized {
            self.initialized = true;
            self.last_prompt_count = stats.prompts;
            self.last_completion_count = stats.completions;
            if effective_state == SessionState::Thinking && stats.prompts > 0 {
                self.active_turn = Some(TurnBaseline {
                    prompt_count: stats.prompts,
                    git_lines: GitLineSnapshot::from_git_state(git_state),
                });
            }
            return changed;
        }

        if stats.prompts > self.last_prompt_count {
            self.last_prompt_count = stats.prompts;
            self.active_turn = Some(TurnBaseline {
                prompt_count: stats.prompts,
                git_lines: GitLineSnapshot::from_git_state(git_state),
            });
            self.state.line_delta = Some(TurnLineDelta::default());
            self.state.latest = None;
            self.pending = None;
            self.state.status = if self.state.enabled {
                if self.api_key.is_some() {
                    RecapStatus::Waiting
                } else {
                    RecapStatus::MissingKey
                }
            } else {
                RecapStatus::Disabled
            };
            changed = true;
        }

        if let Some(turn) = &self.active_turn {
            let line_delta = TurnLineDelta::between(
                &turn.git_lines,
                &GitLineSnapshot::from_git_state(git_state),
            );
            if self.state.line_delta != Some(line_delta) {
                self.state.line_delta = Some(line_delta);
                changed = true;
            }
        }

        let completed_turn = stats.completions > self.last_completion_count
            && effective_state == SessionState::Complete;
        if completed_turn {
            self.last_completion_count = stats.completions;
            changed |= self.start_recap_if_ready(platform, stats, git_state);
        }

        changed
    }

    fn start_recap_if_ready(
        &mut self,
        platform: PlatformKind,
        stats: &PlatformStats,
        git_state: &GitState,
    ) -> bool {
        if !self.state.enabled {
            self.active_turn = None;
            return false;
        }

        let Some(api_key) = self.api_key.clone() else {
            self.state.status = RecapStatus::MissingKey;
            self.active_turn = None;
            return true;
        };

        if self.pending.is_some() {
            return false;
        }

        let Some(turn) = self.active_turn.take() else {
            return false;
        };

        let line_delta =
            TurnLineDelta::between(&turn.git_lines, &GitLineSnapshot::from_git_state(git_state));
        self.state.line_delta = Some(line_delta);
        self.state.status = RecapStatus::Updating;

        let job = RecapJob {
            platform,
            transcript_path: stats.transcript_path.as_ref().map(PathBuf::from),
            prompt_count: turn.prompt_count,
            model: self.state.model.clone(),
            api_key,
            line_delta,
            prs: self.pr_context.clone(),
        };

        let (tx, rx) = mpsc::channel();
        std::thread::spawn(move || {
            let result = generate_turn_recap(job).map_err(|e| e.to_string());
            let _ = tx.send(result);
        });
        self.pending = Some(rx);
        true
    }

    fn poll_pending(&mut self, cwd: &Path) -> bool {
        let Some(rx) = &self.pending else {
            return false;
        };

        match rx.try_recv() {
            Ok(Ok(recap)) => {
                let _ = write_recap_cache(cwd, &recap);
                self.state.line_delta = Some(recap.line_delta);
                self.history.push(recap.clone());
                self.state.latest = Some(recap);
                self.state.status = RecapStatus::Ready;
                self.pending = None;
                true
            }
            Ok(Err(error)) => {
                self.state.status = RecapStatus::Failed(error);
                self.pending = None;
                true
            }
            Err(mpsc::TryRecvError::Empty) => false,
            Err(mpsc::TryRecvError::Disconnected) => {
                self.state.status = RecapStatus::Failed("recap worker stopped".to_string());
                self.pending = None;
                true
            }
        }
    }
}

pub fn run_recap_command(command: RecapCommand) -> Result<()> {
    match command {
        RecapCommand::Enable { api_key, model } => enable_recap(api_key, model),
        RecapCommand::Disable => disable_recap(),
        RecapCommand::Status => print_recap_status(),
    }
}

/// Implements the top-level `crabigator key` shortcut: saves an Anthropic API
/// key (from arg, env var, or prompt) and ensures recaps are enabled.
pub fn run_key_command(api_key: Option<String>) -> Result<()> {
    enable_recap(api_key, None)
}

fn enable_recap(api_key: Option<String>, model: Option<String>) -> Result<()> {
    let key = match api_key {
        Some(key) => key,
        None => std::env::var("ANTHROPIC_API_KEY").unwrap_or_default(),
    };
    let key = if key.trim().is_empty() {
        prompt_for_api_key()?
    } else {
        key
    };

    if key.trim().is_empty() {
        anyhow::bail!("No API key provided");
    }

    Config::write_recap_api_key(&key)?;
    let mut config = Config::load().unwrap_or_default();
    config.recap_enabled = true;
    if let Some(model) = model {
        config.recap_model = Some(model);
    } else if config.recap_model.is_none() {
        config.recap_model = Some(DEFAULT_RECAP_MODEL.to_string());
    }
    config.save()?;

    println!(
        "Recaps enabled with {}.",
        config.recap_model.as_deref().unwrap_or(DEFAULT_RECAP_MODEL)
    );
    Ok(())
}

fn disable_recap() -> Result<()> {
    let mut config = Config::load().unwrap_or_default();
    config.recap_enabled = false;
    config.save()?;
    Config::remove_recap_api_key()?;
    println!("Recaps disabled and stored API key removed.");
    Ok(())
}

fn print_recap_status() -> Result<()> {
    let config = Config::load().unwrap_or_default();
    let stored_key = Config::read_recap_api_key()?.is_some();
    let env_key = read_anthropic_api_key_env().is_some();
    println!("enabled: {}", config.recap_enabled);
    println!(
        "model: {}",
        config.recap_model.as_deref().unwrap_or(DEFAULT_RECAP_MODEL)
    );
    let key_source = if stored_key {
        "stored"
    } else if env_key {
        "env (ANTHROPIC_API_KEY)"
    } else {
        "missing"
    };
    println!("api_key: {}", key_source);
    Ok(())
}

pub(crate) fn read_anthropic_api_key_env() -> Option<String> {
    std::env::var("ANTHROPIC_API_KEY")
        .ok()
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

fn prompt_for_api_key() -> Result<String> {
    print!("Anthropic API key: ");
    io::stdout().flush()?;
    let mut key = String::new();
    io::stdin().read_line(&mut key)?;
    Ok(key.trim().to_string())
}

fn generate_turn_recap(job: RecapJob) -> Result<TurnRecap> {
    let transcript = collect_latest_turn(&job)?;
    let slack_threads = transcript
        .user_prompt
        .as_deref()
        .map(extract_threads)
        .unwrap_or_default();
    if transcript.activity.trim().is_empty() {
        return Ok(fallback_recap(
            &job,
            "The agent completed the turn without captured transcript output.",
            slack_threads,
        ));
    }

    let request = build_anthropic_request(&job, &transcript, &slack_threads);
    let response = call_anthropic(&job.api_key, request)?;
    parse_recap_response(&job, &response, &slack_threads).or_else(|_| {
        Ok(fallback_recap(
            &job,
            "The agent completed the turn. The recap response could not be parsed, so check the live output for details.",
            slack_threads,
        ))
    })
}

#[derive(Debug)]
pub(crate) struct TurnTranscript {
    pub(crate) user_prompt: Option<String>,
    pub(crate) activity: String,
}

fn collect_latest_turn(job: &RecapJob) -> Result<TurnTranscript> {
    collect_latest_turn_text(job.platform, job.transcript_path.as_deref())
}

/// Read and condense the most recent turn from a platform transcript log.
/// Shared with the title generator, which summarizes the same activity into a
/// short window title.
pub(crate) fn collect_latest_turn_text(
    platform: PlatformKind,
    transcript_path: Option<&Path>,
) -> Result<TurnTranscript> {
    let Some(path) = transcript_path else {
        return Ok(TurnTranscript {
            user_prompt: None,
            activity: String::new(),
        });
    };

    let content = fs::read_to_string(path)
        .with_context(|| format!("Failed to read transcript {}", path.display()))?;
    let mut transcript = match platform {
        PlatformKind::Claude => collect_claude_latest_turn(&content),
        PlatformKind::Codex => collect_codex_latest_turn(&content),
    };
    transcript.activity =
        redact_sensitive(&truncate_start(&transcript.activity, MAX_TRANSCRIPT_CHARS));
    transcript.user_prompt = transcript
        .user_prompt
        .map(|prompt| redact_sensitive(&truncate_start(&prompt, 2_000)));
    Ok(transcript)
}

fn collect_claude_latest_turn(content: &str) -> TurnTranscript {
    let mut user_prompt = None;
    let mut activity = String::new();
    let mut after_user_prompt = false;

    for line in content.lines() {
        let Ok(entry) = serde_json::from_str::<Value>(line) else {
            continue;
        };
        match entry.get("type").and_then(|v| v.as_str()) {
            Some("user") => {
                let Some(message_content) = entry.get("message").and_then(|m| m.get("content"))
                else {
                    continue;
                };
                if let Some(prompt) = message_content.as_str() {
                    user_prompt = Some(prompt.trim().to_string());
                    activity.clear();
                    after_user_prompt = true;
                } else if after_user_prompt {
                    append_tool_results(&mut activity, message_content);
                }
            }
            Some("assistant") if after_user_prompt => {
                if let Some(message_content) = entry.get("message").and_then(|m| m.get("content")) {
                    append_assistant_content(&mut activity, message_content);
                }
            }
            _ => {}
        }
    }

    TurnTranscript {
        user_prompt,
        activity,
    }
}

fn collect_codex_latest_turn(content: &str) -> TurnTranscript {
    let mut user_prompt = None;
    let mut activity = String::new();
    let mut after_user_prompt = false;

    for line in content.lines() {
        let Ok(entry) = serde_json::from_str::<Value>(line) else {
            continue;
        };
        let entry_type = entry.get("type").and_then(|v| v.as_str());
        let payload = entry.get("payload").unwrap_or(&Value::Null);

        match entry_type {
            Some("response_item") => match payload.get("type").and_then(|v| v.as_str()) {
                Some("message") if payload.get("role").and_then(|v| v.as_str()) == Some("user") => {
                    let prompt = codex_message_text(payload);
                    if !prompt.trim().is_empty() && !is_codex_bootstrap(&prompt) {
                        user_prompt = Some(prompt.trim().to_string());
                        activity.clear();
                        after_user_prompt = true;
                    }
                }
                Some("message")
                    if after_user_prompt
                        && payload.get("role").and_then(|v| v.as_str()) == Some("assistant") =>
                {
                    let text = codex_message_text(payload);
                    if !text.trim().is_empty() {
                        push_section(&mut activity, "assistant", text.trim());
                    }
                }
                Some("function_call") if after_user_prompt => {
                    let name = payload
                        .get("name")
                        .and_then(|v| v.as_str())
                        .unwrap_or("tool");
                    let args = payload
                        .get("arguments")
                        .map(format_json_preview)
                        .unwrap_or_default();
                    push_section(&mut activity, "tool", &format!("{} {}", name, args));
                }
                Some("function_call_output") if after_user_prompt => {
                    let output = payload
                        .get("output")
                        .and_then(|v| v.as_str())
                        .unwrap_or_default();
                    if !output.trim().is_empty() {
                        push_section(
                            &mut activity,
                            "tool_result",
                            &truncate_end(output.trim(), MAX_TOOL_RESULT_CHARS),
                        );
                    }
                }
                Some("custom_tool_call") if after_user_prompt => {
                    let name = payload
                        .get("name")
                        .and_then(|v| v.as_str())
                        .unwrap_or("tool");
                    let input = payload
                        .get("input")
                        .map(format_codex_custom_tool_preview)
                        .unwrap_or_default();
                    push_section(&mut activity, "tool", &format!("{} {}", name, input));
                }
                Some("custom_tool_call_output") if after_user_prompt => {
                    let output = codex_custom_tool_output_text(payload);
                    if !output.trim().is_empty() {
                        push_section(
                            &mut activity,
                            "tool_result",
                            &truncate_end(output.trim(), MAX_TOOL_RESULT_CHARS),
                        );
                    }
                }
                _ => {}
            },
            Some("event_msg") => match payload.get("type").and_then(|v| v.as_str()) {
                Some("user_message") => {
                    let prompt = payload
                        .get("message")
                        .or_else(|| payload.get("text"))
                        .and_then(|v| v.as_str())
                        .unwrap_or_default();
                    if !prompt.trim().is_empty() && !is_codex_bootstrap(prompt) {
                        user_prompt = Some(prompt.trim().to_string());
                        activity.clear();
                        after_user_prompt = true;
                    }
                }
                Some("agent_message") if after_user_prompt => {
                    let text = payload
                        .get("message")
                        .or_else(|| payload.get("text"))
                        .and_then(|v| v.as_str())
                        .unwrap_or_default();
                    if !text.trim().is_empty() {
                        push_section(&mut activity, "assistant", text.trim());
                    }
                }
                _ => {}
            },
            _ => {}
        }
    }

    TurnTranscript {
        user_prompt,
        activity,
    }
}

fn append_assistant_content(activity: &mut String, content: &Value) {
    match content {
        Value::String(text) => push_section(activity, "assistant", text.trim()),
        Value::Array(blocks) => {
            for block in blocks {
                match block.get("type").and_then(|v| v.as_str()) {
                    Some("text") => {
                        if let Some(text) = block.get("text").and_then(|v| v.as_str()) {
                            push_section(activity, "assistant", text.trim());
                        }
                    }
                    Some("tool_use") => {
                        let name = block.get("name").and_then(|v| v.as_str()).unwrap_or("tool");
                        let input = block
                            .get("input")
                            .map(format_json_preview)
                            .unwrap_or_default();
                        push_section(activity, "tool", &format!("{} {}", name, input));
                    }
                    _ => {}
                }
            }
        }
        _ => {}
    }
}

fn append_tool_results(activity: &mut String, content: &Value) {
    let Value::Array(results) = content else {
        return;
    };
    for result in results {
        let Some(result_content) = result.get("content") else {
            continue;
        };
        let text = match result_content {
            Value::String(text) => text.clone(),
            Value::Array(parts) => parts
                .iter()
                .filter_map(|part| part.get("text").and_then(|v| v.as_str()))
                .collect::<Vec<_>>()
                .join("\n"),
            other => format_json_preview(other),
        };
        if !text.trim().is_empty() {
            push_section(
                activity,
                "tool_result",
                &truncate_end(text.trim(), MAX_TOOL_RESULT_CHARS),
            );
        }
    }
}

fn codex_message_text(payload: &Value) -> String {
    let Some(content) = payload.get("content").and_then(|v| v.as_array()) else {
        return String::new();
    };
    content
        .iter()
        .filter_map(|entry| entry.get("text").and_then(|v| v.as_str()))
        .collect::<Vec<_>>()
        .join("\n")
}

fn format_codex_custom_tool_preview(value: &Value) -> String {
    match value {
        Value::String(text) => truncate_middle(text, 1_200),
        other => format_json_preview(other),
    }
}

fn codex_custom_tool_output_text(payload: &Value) -> String {
    let Some(output) = payload.get("output") else {
        return String::new();
    };
    match output {
        Value::String(text) => text.clone(),
        Value::Array(parts) => parts
            .iter()
            .filter_map(|part| part.get("text").and_then(|v| v.as_str()))
            .collect::<Vec<_>>()
            .join("\n"),
        other => format_json_preview(other),
    }
}

fn is_codex_bootstrap(text: &str) -> bool {
    text.contains("<INSTRUCTIONS>")
        || text.contains("<environment_context>")
        || text.contains("# AGENTS.md instructions")
}

fn push_section(out: &mut String, label: &str, text: &str) {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return;
    }
    out.push_str("\n[");
    out.push_str(label);
    out.push_str("]\n");
    out.push_str(trimmed);
    out.push('\n');
}

fn format_json_preview(value: &Value) -> String {
    match value {
        Value::String(text) => truncate_end(text, 600),
        other => serde_json::to_string(other)
            .map(|s| truncate_end(&s, 900))
            .unwrap_or_default(),
    }
}

fn build_anthropic_request(
    job: &RecapJob,
    transcript: &TurnTranscript,
    slack_threads: &[SlackThread],
) -> Value {
    let size_hint = transcript.activity.chars().count();
    let preferred_variant = if size_hint < 3_500 {
        "brief"
    } else {
        "bullets"
    };
    let user_prompt = transcript
        .user_prompt
        .as_deref()
        .unwrap_or("(last user prompt unavailable)");

    let (title_shape, title_rules) = if job.platform == PlatformKind::Codex {
        (
            ",\"title\":\"\"",
            "- title: 3-6 words in Title Case that name the session's current task. No tool names, quotes, leading symbol, or trailing punctuation.\n",
        )
    } else {
        ("", "")
    };

    let (slack_shape, slack_rules) = if slack_threads.is_empty() {
        (String::new(), String::new())
    } else {
        let urls = slack_threads
            .iter()
            .map(|thread| format!("- {}", thread.url))
            .collect::<Vec<_>>()
            .join("\n");
        (
            ",\"slack_threads\":[{\"url\":\"\",\"channel\":\"\",\"author\":\"\"}]".to_string(),
            format!(
                "- slack_threads: one entry for each URL below, unchanged and in the same order. Set channel to its readable channel name and author to the poster's display name only when the transcript identifies them clearly; otherwise use empty strings.\nSlack permalinks:\n{urls}\n"
            ),
        )
    };

    let (pr_block, pr_shape, pr_rules) = if job.prs.is_empty() {
        (String::new(), "", "")
    } else {
        let list = job
            .prs
            .iter()
            .map(|pr| {
                format!(
                    "- {} [{}, {}] :: {}",
                    pr.label,
                    pr.status,
                    if pr.primary { "primary" } else { "secondary" },
                    pr.url
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        (
            format!("Tracked PRs:\n{list}\n\n"),
            ",\"prs\":[{\"url\":\"\",\"note\":\"\",\"confidence\":\"high|medium|low\"}]",
            "- prs: one entry per tracked PR (same url). note: ≤80 chars on its \
             progress this turn or current blocker. confidence: how confident you \
             are the PR is FINISHED (high = merged/ready, medium = close, low = \
             still cooking or stalled).\n",
        )
    };

    let prompt = format!(
        "Write a Crabigator handoff recap for agent output since the last user-initiated prompt.\n\
         Preferred variant: {preferred_variant}\n\
         Last user prompt, for context only:\n{user_prompt}\n\n\
         {pr_block}Agent activity:\n{}\n\n\
         Return JSON only with this exact shape:\n\
         {{\"variant\":\"brief|bullets\",\"headline\":\"\",\
         \"bullets\":[],\"next_prompt_notes\":[],\"artifacts\":[]{title_shape}{slack_shape}{pr_shape}}}\n\
         Hard length budget — terse > complete sentences:\n\
         - headline: ≤72 chars, no trailing period.\n\
         - bullets: 0-2 items, ≤80 chars each. brief: omit bullets.\n\
         - next_prompt_notes: 0-1 items, ≤80 chars.\n\
         - artifacts: 0-2 items, ≤50 chars each.\n\
         {title_rules}{slack_rules}{pr_rules}Rules:\n\
         - Be terse. Cut filler words. Don't repeat the headline in bullets.\n\
         - Skip code-level details (file names, line numbers, diffs); the Git and Changes widgets cover those.\n\
         - Artifacts = non-code outputs to review (screenshots, logs, URLs, PRs, build reports).\n\
         - If nothing important happened, headline says so plainly and bullets/notes/artifacts are empty.",
        transcript.activity
    );

    // Per-PR notes need extra room beyond the base recap budget.
    let max_tokens = 350
        + 60 * job.prs.len().min(6)
        + 45 * slack_threads.len().min(8)
        + if job.platform == PlatformKind::Codex {
            20
        } else {
            0
        };

    json!({
        "model": job.model,
        "max_tokens": max_tokens,
        "temperature": 0.2,
        "messages": [
            {"role": "user", "content": prompt}
        ]
    })
}

pub(crate) fn call_anthropic(api_key: &str, body: Value) -> Result<String> {
    let api_url = std::env::var("CRABIGATOR_RECAP_API_URL")
        .unwrap_or_else(|_| ANTHROPIC_MESSAGES_URL.to_string());
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("Failed to create recap runtime")?;
    runtime.block_on(async {
        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(45))
            .build()?;
        let response = client
            .post(api_url)
            .header("x-api-key", api_key)
            .header("anthropic-version", ANTHROPIC_VERSION)
            .json(&body)
            .send()
            .await
            .context("Failed to call Anthropic Messages API")?;

        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        if !status.is_success() {
            anyhow::bail!(
                "Anthropic returned {}: {}",
                status,
                truncate_end(&text, 220)
            );
        }
        extract_anthropic_text(&text)
    })
}

fn extract_anthropic_text(response: &str) -> Result<String> {
    let value: Value = serde_json::from_str(response).context("Anthropic response was not JSON")?;
    let text = value
        .get("content")
        .and_then(|v| v.as_array())
        .into_iter()
        .flatten()
        .filter_map(|block| {
            if block.get("type").and_then(|v| v.as_str()) == Some("text") {
                block.get("text").and_then(|v| v.as_str())
            } else {
                None
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    if text.trim().is_empty() {
        anyhow::bail!("Anthropic response did not contain text");
    }
    Ok(text)
}

fn parse_recap_response(
    job: &RecapJob,
    response: &str,
    slack_threads: &[SlackThread],
) -> Result<TurnRecap> {
    let json_text = extract_json_object(response).unwrap_or(response);
    let value: Value = serde_json::from_str(json_text).context("Recap response was not JSON")?;
    let variant = match value.get("variant").and_then(|v| v.as_str()) {
        Some("bullets") => RecapVariant::Bullets,
        _ => RecapVariant::Brief,
    };
    let headline = value
        .get("headline")
        .and_then(|v| v.as_str())
        .map(clean_one_line)
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "The agent completed the latest turn.".to_string());
    let bullets = string_array(&value, "bullets", 3);
    let next_prompt_notes = string_array(&value, "next_prompt_notes", 2);
    let artifacts = string_array(&value, "artifacts", 3);
    let pr_notes = pr_note_array(&value);
    let title = if job.platform == PlatformKind::Codex {
        value
            .get("title")
            .and_then(|value| value.as_str())
            .map(clean_generated_title)
            .filter(|title| !title.is_empty())
    } else {
        None
    };
    let slack_threads = merge_slack_metadata(slack_threads, &value);

    Ok(TurnRecap {
        prompt_count: job.prompt_count,
        generated_at: now_unix_ms(),
        title,
        variant,
        headline,
        bullets,
        next_prompt_notes,
        artifacts,
        line_delta: job.line_delta,
        pr_notes,
        slack_threads,
    })
}

/// Apply optional model-derived channel and poster names to the deterministic
/// permalink list. Unknown or invented URLs never enter session state.
fn merge_slack_metadata(threads: &[SlackThread], value: &Value) -> Vec<SlackThread> {
    let candidates = value
        .get("slack_threads")
        .and_then(|value| value.as_array())
        .map(Vec::as_slice)
        .unwrap_or_default();

    threads
        .iter()
        .map(|thread| {
            let candidate = candidates
                .iter()
                .find(|entry| entry.get("url").and_then(|url| url.as_str()) == Some(&thread.url));
            let channel = candidate
                .and_then(|entry| entry.get("channel"))
                .and_then(|channel| channel.as_str())
                .map(clean_one_line)
                .map(|channel| channel.trim_start_matches('#').to_string())
                .filter(|channel| !channel.is_empty())
                .map(|channel| truncate_end(&channel, 60))
                .or_else(|| thread.channel.clone());
            let author = candidate
                .and_then(|entry| entry.get("author"))
                .and_then(|author| author.as_str())
                .map(clean_one_line)
                .filter(|author| !author.is_empty())
                .map(|author| truncate_end(&author, 60));
            SlackThread {
                channel,
                author,
                ..thread.clone()
            }
        })
        .collect()
}

/// The per-PR judgments in a recap response, keeping only well-formed entries.
fn pr_note_array(value: &Value) -> Vec<PrRecapNote> {
    value
        .get("prs")
        .and_then(|v| v.as_array())
        .into_iter()
        .flatten()
        .filter_map(|entry| {
            let url = entry.get("url")?.as_str()?.trim().to_string();
            if url.is_empty() {
                return None;
            }
            let note = entry
                .get("note")
                .and_then(|v| v.as_str())
                .map(clean_one_line)
                .map(|s| truncate_end(&s, 120))
                .unwrap_or_default();
            let confidence = match entry.get("confidence").and_then(|v| v.as_str()) {
                Some(c @ ("high" | "medium" | "low")) => c.to_string(),
                _ => String::new(),
            };
            if note.is_empty() && confidence.is_empty() {
                return None;
            }
            Some(PrRecapNote {
                url,
                note,
                confidence,
            })
        })
        .take(12)
        .collect()
}

fn fallback_recap(job: &RecapJob, headline: &str, slack_threads: Vec<SlackThread>) -> TurnRecap {
    TurnRecap {
        prompt_count: job.prompt_count,
        generated_at: now_unix_ms(),
        title: None,
        variant: RecapVariant::Brief,
        headline: headline.to_string(),
        bullets: Vec::new(),
        next_prompt_notes: Vec::new(),
        artifacts: Vec::new(),
        line_delta: job.line_delta,
        pr_notes: Vec::new(),
        slack_threads,
    }
}

fn string_array(value: &Value, key: &str, limit: usize) -> Vec<String> {
    value
        .get(key)
        .and_then(|v| v.as_array())
        .into_iter()
        .flatten()
        .filter_map(|v| v.as_str())
        .map(clean_one_line)
        .filter(|s| !s.is_empty())
        .take(limit)
        .collect()
}

fn clean_one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn extract_json_object(text: &str) -> Option<&str> {
    let start = text.find('{')?;
    let end = text.rfind('}')?;
    (end >= start).then_some(&text[start..=end])
}

fn redact_sensitive(text: &str) -> String {
    let mut redacted = text.to_string();
    let patterns = [
        r"sk-ant-[A-Za-z0-9_\-]{12,}",
        r"sk-[A-Za-z0-9_\-]{20,}",
        r"github_pat_[A-Za-z0-9_]{20,}",
        r"gh[pousr]_[A-Za-z0-9_]{20,}",
        r"AKIA[0-9A-Z]{16}",
        r#"(?i)(api[_-]?key|token|secret|password)(['"\s:=]+)[A-Za-z0-9_\-./+=]{12,}"#,
    ];
    for pattern in patterns {
        if let Ok(regex) = Regex::new(pattern) {
            redacted = regex.replace_all(&redacted, "$1$2[REDACTED]").to_string();
        }
    }
    redacted
}

fn truncate_start(text: &str, max_chars: usize) -> String {
    let count = text.chars().count();
    if count <= max_chars {
        return text.to_string();
    }
    let keep: String = text.chars().skip(count - max_chars).collect();
    format!(
        "... omitted {} earlier chars ...\n{}",
        count - max_chars,
        keep
    )
}

fn truncate_end(text: &str, max_chars: usize) -> String {
    let count = text.chars().count();
    if count <= max_chars {
        text.to_string()
    } else {
        let kept: String = text.chars().take(max_chars).collect();
        format!("{}...", kept)
    }
}

fn truncate_middle(text: &str, max_chars: usize) -> String {
    let count = text.chars().count();
    if count <= max_chars {
        return text.to_string();
    }
    let marker = "\n... omitted middle ...\n";
    let available = max_chars.saturating_sub(marker.chars().count());
    let head_chars = available / 2;
    let tail_chars = available - head_chars;
    let head: String = text.chars().take(head_chars).collect();
    let tail: String = text.chars().skip(count - tail_chars).collect();
    format!("{head}{marker}{tail}")
}

fn now_unix_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

fn recap_age_bucket(generated_at_ms: u64) -> u64 {
    let elapsed_secs = now_unix_ms().saturating_sub(generated_at_ms) / 1000;
    if elapsed_secs < 60 {
        0
    } else {
        elapsed_secs / 60
    }
}

fn write_recap_cache(cwd: &Path, recap: &TurnRecap) -> Result<()> {
    let session_id = std::env::var("CRABIGATOR_SESSION_ID").unwrap_or_default();
    if session_id.is_empty() {
        return Ok(());
    }
    let session_dir = PathBuf::from(format!("/tmp/crabigator-{}", session_id));
    fs::create_dir_all(&session_dir)?;
    let path = session_dir.join("recap.json");
    let tmp_path = path.with_extension("tmp");
    let json = serde_json::to_string_pretty(&json!({
        "cwd": cwd.to_string_lossy(),
        "recap": recap,
    }))?;
    fs::write(&tmp_path, json)?;
    fs::rename(&tmp_path, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_recap_json_with_wrapping_text() {
        let job = RecapJob {
            platform: PlatformKind::Claude,
            transcript_path: None,
            prompt_count: 2,
            model: DEFAULT_RECAP_MODEL.to_string(),
            api_key: "key".to_string(),
            prs: Vec::new(),
            line_delta: TurnLineDelta {
                additions: 12,
                deletions: 3,
            },
        };

        let recap = parse_recap_response(
            &job,
            "```json\n{\"variant\":\"bullets\",\"headline\":\"Changed the flow.\",\"bullets\":[\"One\"],\"next_prompt_notes\":[\"Check behavior\"],\"artifacts\":[\"test log\"]}\n```",
            &[],
        )
        .unwrap();

        assert_eq!(recap.variant, RecapVariant::Bullets);
        assert_eq!(recap.headline, "Changed the flow.");
        assert_eq!(recap.bullets, vec!["One"]);
        assert_eq!(recap.next_prompt_notes, vec!["Check behavior"]);
        assert_eq!(recap.artifacts, vec!["test log"]);
        assert_eq!(recap.line_delta.additions, 12);
        assert!(recap.pr_notes.is_empty());

        // Per-PR judgments parse when present; malformed entries are dropped.
        let with_prs = parse_recap_response(
            &job,
            r#"{"variant":"brief","headline":"CI green on the fix",
                "bullets":[],"next_prompt_notes":[],"artifacts":[],
                "prs":[
                    {"url":"https://github.com/o/r/pull/9","note":"CI green, awaiting review","confidence":"medium"},
                    {"url":"","note":"orphan","confidence":"high"},
                    {"url":"https://github.com/o/r/pull/10","confidence":"nonsense"}
                ]}"#,
            &[],
        )
        .unwrap();
        assert_eq!(with_prs.pr_notes.len(), 1);
        assert_eq!(with_prs.pr_notes[0].url, "https://github.com/o/r/pull/9");
        assert_eq!(with_prs.pr_notes[0].note, "CI green, awaiting review");
        assert_eq!(with_prs.pr_notes[0].confidence, "medium");

        let mut codex_job = job.clone();
        codex_job.platform = PlatformKind::Codex;
        let slack = extract_threads(
            "https://tavus.slack.com/archives/C123/p1754404040123456?thread_ts=1754400000.000000&cid=C123",
        );
        let codex = parse_recap_response(
            &codex_job,
            r#"{"variant":"brief","headline":"Linked the thread","title":"Track Slack Discussions.",
                "bullets":[],"next_prompt_notes":[],"artifacts":[],
                "slack_threads":[
                    {"url":"https://tavus.slack.com/archives/C123/p1754404040123456?thread_ts=1754400000.000000&cid=C123","channel":"builder","author":"Sam Clay"},
                    {"url":"https://invented.slack.com/archives/C9/p1754404040123456","author":"Nope"}
                ]}"#,
            &slack,
        )
        .unwrap();
        assert_eq!(codex.title.as_deref(), Some("Track Slack Discussions"));
        assert_eq!(codex.slack_threads.len(), 1);
        assert_eq!(codex.slack_threads[0].channel.as_deref(), Some("builder"));
        assert_eq!(codex.slack_threads[0].author.as_deref(), Some("Sam Clay"));
    }

    #[test]
    fn claude_collector_resets_at_latest_user_prompt() {
        let transcript = r#"{"type":"user","message":{"content":"old prompt"}}
{"type":"assistant","message":{"content":[{"type":"text","text":"old answer"}]}}
{"type":"user","message":{"content":"new prompt"}}
{"type":"assistant","message":{"content":[{"type":"text","text":"new answer"},{"type":"tool_use","name":"Bash","input":{"command":"cargo test"}}]}}"#;

        let turn = collect_claude_latest_turn(transcript);
        assert_eq!(turn.user_prompt.as_deref(), Some("new prompt"));
        assert!(turn.activity.contains("new answer"));
        assert!(turn.activity.contains("cargo test"));
        assert!(!turn.activity.contains("old answer"));
    }

    #[test]
    fn codex_collector_resets_at_latest_user_prompt() {
        let transcript = r#"{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"old prompt"}]}}
{"type":"event_msg","payload":{"type":"agent_message","message":"old answer","phase":"final"}}
{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"new prompt"}]}}
{"type":"event_msg","payload":{"type":"agent_message","message":"new answer","phase":"final"}}
{"type":"response_item","payload":{"type":"function_call","name":"exec_command","arguments":"{\"cmd\":\"cargo test\"}"}}
{"type":"response_item","payload":{"type":"custom_tool_call","name":"exec","input":"const r = await tools.exec_command({cmd:\"gh pr view 2469 --repo Tavus-Engineering/request-handler\"}); text(r.output);"}}
{"type":"response_item","payload":{"type":"custom_tool_call_output","output":[{"type":"input_text","text":"https://github.com/Tavus-Engineering/request-handler/pull/2469"}]}}"#;

        let turn = collect_codex_latest_turn(transcript);
        assert_eq!(turn.user_prompt.as_deref(), Some("new prompt"));
        assert!(turn.activity.contains("new answer"));
        assert!(turn.activity.contains("cargo test"));
        assert!(turn.activity.contains("gh pr view 2469"));
        assert!(turn
            .activity
            .contains("https://github.com/Tavus-Engineering/request-handler/pull/2469"));
        assert!(!turn.activity.contains("old answer"));
    }

    #[test]
    fn collect_latest_turn_without_transcript_path_is_empty() {
        let job = RecapJob {
            platform: PlatformKind::Codex,
            transcript_path: None,
            prompt_count: 1,
            model: DEFAULT_RECAP_MODEL.to_string(),
            api_key: "key".to_string(),
            prs: Vec::new(),
            line_delta: TurnLineDelta::default(),
        };

        let turn = collect_latest_turn(&job).unwrap();
        assert!(turn.user_prompt.is_none());
        assert!(turn.activity.is_empty());
    }

    #[test]
    fn redacts_common_secrets() {
        let text =
            "api_key = sk-ant-1234567890abcdefghijklmnop and token: ghp_1234567890abcdefghijklmnop";
        let redacted = redact_sensitive(text);
        assert!(redacted.contains("[REDACTED]"));
        assert!(!redacted.contains("sk-ant-1234567890"));
        assert!(!redacted.contains("ghp_1234567890"));
    }

    #[test]
    fn hides_until_a_real_recap_exists() {
        let state = RecapState {
            enabled: true,
            status: RecapStatus::Waiting,
            latest: None,
            line_delta: None,
            model: DEFAULT_RECAP_MODEL.to_string(),
        };

        assert!(!state.prefers_handoff());
    }

    #[test]
    fn failed_status_takes_over_handoff_until_next_turn() {
        // Failed status reserves the handoff strip even without a `latest`.
        let mut state = RecapState {
            enabled: true,
            status: RecapStatus::Failed("Anthropic returned 400".to_string()),
            latest: None,
            line_delta: None,
            model: DEFAULT_RECAP_MODEL.to_string(),
        };
        assert!(state.prefers_handoff());

        // After the next prompt resets status, the strip releases.
        state.status = RecapStatus::Updating;
        assert!(!state.prefers_handoff());
    }

    #[test]
    fn enabled_toast_visibility_obeys_status_and_clock() {
        // Fresh manager with a working key → toast visible.
        let mut manager = RecapManager {
            state: RecapState {
                enabled: true,
                status: RecapStatus::Waiting,
                latest: None,
                line_delta: None,
                model: DEFAULT_RECAP_MODEL.to_string(),
            },
            api_key: Some("test".to_string()),
            last_prompt_count: 0,
            last_completion_count: 0,
            initialized: false,
            active_turn: None,
            pending: None,
            started_at: Instant::now(),
            history: Vec::new(),
            pr_context: Vec::new(),
        };
        assert!(manager.enabled_toast_visible());

        // Disabled / MissingKey statuses suppress the toast.
        manager.state.status = RecapStatus::Disabled;
        assert!(!manager.enabled_toast_visible());
        manager.state.status = RecapStatus::MissingKey;
        assert!(!manager.enabled_toast_visible());

        // After the toast window elapses, the toast is gone.
        manager.state.status = RecapStatus::Ready;
        manager.started_at = Instant::now()
            .checked_sub(ENABLED_TOAST_DURATION + Duration::from_secs(1))
            .expect("clock arithmetic");
        assert!(!manager.enabled_toast_visible());
    }

    #[test]
    fn prompt_submission_dismisses_existing_recap() {
        let mut manager = RecapManager {
            state: RecapState {
                enabled: true,
                status: RecapStatus::Ready,
                latest: Some(TurnRecap {
                    prompt_count: 1,
                    generated_at: 1,
                    title: Some("Previous Task".to_string()),
                    variant: RecapVariant::Brief,
                    headline: "Previous recap".to_string(),
                    bullets: Vec::new(),
                    next_prompt_notes: Vec::new(),
                    artifacts: Vec::new(),
                    line_delta: TurnLineDelta::default(),
                    pr_notes: Vec::new(),
                    slack_threads: Vec::new(),
                }),
                line_delta: Some(TurnLineDelta::default()),
                model: DEFAULT_RECAP_MODEL.to_string(),
            },
            api_key: Some("test".to_string()),
            last_prompt_count: 1,
            last_completion_count: 1,
            initialized: true,
            active_turn: None,
            pending: None,
            started_at: Instant::now(),
            history: Vec::new(),
            pr_context: Vec::new(),
        };
        let stats = PlatformStats {
            prompts: 2,
            completions: 1,
            ..PlatformStats::default()
        };

        let changed = manager.handle_platform_update(
            PlatformKind::Codex,
            &stats,
            SessionState::Thinking,
            &GitState::default(),
            Path::new("/tmp"),
        );

        assert!(changed);
        assert!(manager.state.latest.is_none());
        assert!(!manager.state.prefers_handoff());
        assert!(matches!(manager.state.status, RecapStatus::Waiting));
    }
}
