//! Codex title helpers.
//!
//! Claude Code publishes its own OSC title. Codex titles are generated by the
//! existing per-turn recap request so the title and recap always describe the
//! same completed turn.

use crate::platforms::PlatformKind;

/// Marker prefixed to titles generated by Crabigator rather than the agent.
pub const GENERATED_TITLE_MARKER: &str = "⟁ ";

/// Word budget for a generated title.
const MAX_TITLE_WORDS: usize = 6;

/// Normalize the recap model's title into a clean, bounded single line.
pub(crate) fn clean_generated_title(text: &str) -> String {
    for raw in text.lines() {
        let line = raw
            .trim()
            .trim_matches(|c: char| c == '"' || c == '\'' || c == '`')
            .trim_end_matches(['.', '!', ',', ':', ';'])
            .trim();
        if line.is_empty() {
            continue;
        }
        return line
            .split_whitespace()
            .take(MAX_TITLE_WORDS)
            .collect::<Vec<_>>()
            .join(" ");
    }
    String::new()
}

/// Choose the title shown by Crabigator without allowing generated recap
/// titles to replace Claude Code's native OSC title.
pub(crate) fn display_title(
    platform: PlatformKind,
    native_title: Option<&str>,
    recap_title: Option<&str>,
) -> Option<String> {
    if platform == PlatformKind::Codex {
        if let Some(title) = recap_title.filter(|title| !title.is_empty()) {
            return Some(format!("{GENERATED_TITLE_MARKER}{title}"));
        }
    }
    native_title.map(str::to_string)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_title_bounds_words_and_strips_decoration() {
        assert_eq!(
            clean_generated_title("\"Refactor The Title Rendering Path Now Please\"."),
            "Refactor The Title Rendering Path Now"
        );
        assert_eq!(
            clean_generated_title("```\nFix Branch Truncation\n```"),
            "Fix Branch Truncation"
        );
        assert_eq!(
            clean_generated_title("Add Dashboard Auth Flow"),
            "Add Dashboard Auth Flow"
        );
    }

    #[test]
    fn recap_titles_replace_codex_but_not_claude_titles() {
        assert_eq!(
            display_title(
                PlatformKind::Codex,
                Some("crabigator"),
                Some("Track Slack Threads")
            )
            .as_deref(),
            Some("⟁ Track Slack Threads")
        );
        assert_eq!(
            display_title(
                PlatformKind::Claude,
                Some("Native Claude Title"),
                Some("Ignored Recap Title")
            )
            .as_deref(),
            Some("Native Claude Title")
        );
    }
}
