//! Session title helpers.
//!
//! Claude Code publishes its own OSC title. Codex titles are generated by the
//! existing per-turn recap request so the title and recap always describe the
//! same completed turn. Provider markers make the two session types easy to
//! distinguish wherever those titles appear.

use crate::platforms::PlatformKind;

/// Marker prefixed to Codex session titles.
pub const CODEX_TITLE_MARKER: &str = "⟁  ";
/// Marker prefixed to Claude session titles.
pub const CLAUDE_TITLE_MARKER: &str = "ᛝ  ";
/// Marker used when a PR aggregates both Codex and Claude sessions.
pub(crate) const MIXED_PROVIDER_TITLE_MARKER: &str = "⟁ᛝ  ";

pub(crate) const fn provider_title_marker(platform: PlatformKind) -> &'static str {
    match platform {
        PlatformKind::Claude => CLAUDE_TITLE_MARKER,
        PlatformKind::Codex => CODEX_TITLE_MARKER,
    }
}

/// Word budget for a generated title.
const MAX_TITLE_WORDS: usize = 6;

/// Normalize the recap model's title into a clean, bounded single line.
pub(crate) fn clean_generated_title(text: &str) -> String {
    for raw in text.lines() {
        let line = raw
            .trim()
            .trim_matches(|c: char| c == '"' || c == '\'' || c == '`')
            .trim_end_matches(['.', '!', ',', ':', ';'])
            .trim();
        if line.is_empty() {
            continue;
        }
        return line
            .split_whitespace()
            .take(MAX_TITLE_WORDS)
            .collect::<Vec<_>>()
            .join(" ");
    }
    String::new()
}

/// Remove a provider marker while accepting one- and two-space variants.
pub(crate) fn strip_provider_title_marker(title: &str) -> &str {
    for marker in [CODEX_TITLE_MARKER, CLAUDE_TITLE_MARKER, "⟁ ", "ᛝ "] {
        if let Some(title) = title.strip_prefix(marker) {
            return title;
        }
    }
    title
}

/// Identify the provider encoded by a current or legacy title marker.
pub(crate) fn marked_title_platform(title: &str) -> Option<PlatformKind> {
    [PlatformKind::Codex, PlatformKind::Claude]
        .into_iter()
        .find(|platform| title.starts_with(provider_title_marker(*platform).trim_end()))
}

/// Prefix one normalized title with its provider marker.
pub(crate) fn mark_provider_title(platform: PlatformKind, title: &str) -> String {
    format!(
        "{}{}",
        provider_title_marker(platform),
        strip_provider_title_marker(title)
    )
}

/// Choose the title shown by Crabigator without allowing generated recap
/// titles to replace Claude Code's native OSC title.
pub(crate) fn display_title(
    platform: PlatformKind,
    native_title: Option<&str>,
    recap_title: Option<&str>,
) -> Option<String> {
    let native_title = native_title
        .map(strip_provider_title_marker)
        .filter(|title| !title.is_empty());
    let recap_title = recap_title
        .map(strip_provider_title_marker)
        .filter(|title| !title.is_empty());
    let title = match platform {
        PlatformKind::Claude => native_title,
        PlatformKind::Codex => recap_title.or(native_title),
    };
    title.map(|title| mark_provider_title(platform, title))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_title_bounds_words_and_strips_decoration() {
        assert_eq!(
            clean_generated_title("\"Refactor The Title Rendering Path Now Please\"."),
            "Refactor The Title Rendering Path Now"
        );
        assert_eq!(
            clean_generated_title("```\nFix Branch Truncation\n```"),
            "Fix Branch Truncation"
        );
        assert_eq!(
            clean_generated_title("Add Dashboard Auth Flow"),
            "Add Dashboard Auth Flow"
        );
    }

    #[test]
    fn provider_markers_distinguish_codex_and_claude_titles() {
        assert_eq!(
            display_title(
                PlatformKind::Codex,
                Some("crabigator"),
                Some("Track Slack Threads")
            )
            .as_deref(),
            Some("⟁  Track Slack Threads")
        );
        assert_eq!(
            display_title(PlatformKind::Codex, Some("Codex CLI"), None).as_deref(),
            Some("⟁  Codex CLI")
        );
        assert_eq!(
            display_title(PlatformKind::Codex, Some("Codex CLI"), Some("⟁  ")).as_deref(),
            Some("⟁  Codex CLI")
        );
        assert_eq!(
            display_title(
                PlatformKind::Claude,
                Some("Native Claude Title"),
                Some("Ignored Recap Title")
            )
            .as_deref(),
            Some("ᛝ  Native Claude Title")
        );
    }

    #[test]
    fn provider_marker_stripping_accepts_both_providers_and_spacing() {
        assert_eq!(strip_provider_title_marker("⟁ Old Title"), "Old Title");
        assert_eq!(strip_provider_title_marker("⟁  New Title"), "New Title");
        assert_eq!(strip_provider_title_marker("ᛝ Old Title"), "Old Title");
        assert_eq!(strip_provider_title_marker("ᛝ  New Title"), "New Title");
        assert_eq!(
            marked_title_platform("⟁ Existing Title"),
            Some(PlatformKind::Codex)
        );
        assert_eq!(
            marked_title_platform("ᛝ  Existing Title"),
            Some(PlatformKind::Claude)
        );
        assert_eq!(
            strip_provider_title_marker("⟁Native Title"),
            "⟁Native Title"
        );
        assert_eq!(strip_provider_title_marker("Native Title"), "Native Title");
    }
}
